# Generated by Django 4.0.5 on 2022-06-21 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imoveis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cabecalho', models.CharField(blank=True, max_length=150, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('1', 'CASA'), ('2', 'TERRENO'), ('3', 'APARTAMENTO')], max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Imoveis',
                'verbose_name_plural': 'Imoveis',
                'db_table': 'imoveis',
                'ordering': ['-id'],
            },
        ),
    ]
