# Generated by Django 4.0.5 on 2022-06-21 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imoveis',
            options={'ordering': ['-id'], 'verbose_name': 'Imovel', 'verbose_name_plural': 'Imoveis'},
        ),
    ]
