# Generated by Django 4.0.5 on 2022-06-21 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0003_imoveis_imagens'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemImoveis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(upload_to='images_imoveis/')),
            ],
            options={
                'verbose_name': 'Imagem',
                'verbose_name_plural': 'Imagens',
                'db_table': 'imagens_imoveis',
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveField(
            model_name='imoveis',
            name='imagens',
        ),
        migrations.AddField(
            model_name='imoveis',
            name='imagens',
            field=models.ManyToManyField(to='imoveis.imagemimoveis'),
        ),
    ]
